### PR TITLE
Fix SelectMenu#getPlaceholder return value

### PR DESCRIPTION
**Pull request by skykatik**
**Description:** Fixes an incorrect method return value

**Justification:** Method `#getPlaceholder` returns select menu's `customId` instead of `placeholder`

### CODE REVIEW

**Comment by darichey** [comment]
Whoops, thanks! Could you please change the base to `3.1.x`? You can do that with
```
git rebase --onto 3.1.x master fix-select-menu-placeholder 
```

**Comment by skykatik** [comment]
Hi, yes I can, and I need then execute `git push`? Sorry, I'm using this command for the fist time 😳

**Comment by darichey** [comment]
No problem :)

Yep, you'll need for force push (`git push -f`) because you're rewriting the commit history. I'm not sure if GitHub will automatically pick up the new base, but if not, you'll also need to change the base with the "edit" button at the top of the PR.

Feel free to ask any questions about this in the D4J discord server!

**Review by darichey — APPROVED** [review]
Thanks!

**Review by quanticc — APPROVED** [review]

**Pull request merged**
