### PR TITLE
Rework the CircleCI configuration

### PR DESCRIPTION
**Pull request by Vampire**
The subject says it all.
The failing tests have nothing to do with the CircleCI config per-se, they also fail upon local Gradle call.

### CODE REVIEW

**Comment by austinv11** [comment]
ec7943a and dac2ad6 now makes this redundant

**Comment by Vampire** [comment]
No, they don't make my PR redundant.
The dependency cache saving does not work at all in your version.
Neither do you download the dependencies to save for saving, nor do you calculate the cache key correclty as you have your dependency declarations split into multiple Gradle files.
You can equally well throw out the `restore_cache`, `run` and `save_cache` steps.

Or you can still accept my PR and get:

- Proper dependency cache key calculation from all Gradle files
- Proper saving / restoring of the downloaded dependencies in the CircleCI store
- Proper saving / restoring of the downloaded Gradle distribution in the CircleCI store with appropriate cache key
- Proper saving / restoring of the Gradle build cache in the CircleCI store with appropriate cache key
- Proper restriction of Gradle to two workers (CPU detection of Gradle detects way too many CPUs on CircleCI virtualization and thus uses too many workers which is inefficient)
- Building all that is necessary for a release, including JavaDoc
- Executing Gradle tasks that do not depend on failing Gradle tasks even if some failed, e. g. run tests on other modules that do not depend on tests of failed modules
- Publish the test results into the CircleCI infrastructure properly
- Publish the built JARs including JavaDoc and Sources JARs, the generated Test  Reports and the JavaDoc as directly browsable files in the Artifacts section of the CircleCI build page

All this you do not have currently, so I would totally object in saying my PR is redundant. 

If you don't want my changes fine, I don't care too much, just wanted to help.
I just wanted to make sure that you understand that the changes are not redundant but still important.

**Comment by quanticc** [comment]
Thanks for the help @Vampire . Regarding proper ways to cache stuff, we used the getting started file provided by CircleCI for Gradle, so maybe we should reach out to them to fix it?

Regardless, we will consider these changes as we understand the whole platform and decide what features we would like to use. It's important for us that the entire team knows how this works and this means doing so at a pace we're all comfortable with.

**Comment by Vampire** [comment]
Sure, just wanted to note down what things you get with my changes, feel free to use what you like. 

About the caching, I know it is their suggestion, they just seem to not know how Gradle works and don't really care.  I already told them about it, but feel free to do it again.

**Pull request closed without merging**
