### PR TITLE
Create InteractionValidator

### PR DESCRIPTION
**Pull request by napstr**
**Description:** 
Add an interface to enable devs to implement interaction validators.

**Justification:** 
I'd like to be able to use something else than a proxy to validate discord interactions.

I have tested this concretely with the [Request Verifier by DiscordInteraKTions](https://github.com/LorittaBot/DiscordInteraKTions/tree/main/requests-verifier) (which however appears to require Java 15, so cannot be added or adapted into D4J directly)

### CODE REVIEW

**Comment by darichey** [comment]
Is there a use case for a generic validator instead of just implementing the validation algorithm?

**Comment by napstr** [comment]
The use case is allowing devs to provide a validator on their own terms. The only validator I am aware of at the moment requires Java 15, which is not supported by D4J yet, so it cannot be pulled in directly. It seems that there was another validator based on a 3rd party cryptography package that would be compatible with Java 11 (see https://github.com/LorittaBot/DiscordInteraKTions/commit/37c9e322ee055897f650a7610cb8e10bfac40db7), however for my usage im completely happy with the Java 15 one.
I would like to use that validator, I don't want do the additional work of implementing a Java8/11 compatible validator when there is already a working one that I have tested and found adequate. I'm sure the devs who are stuck on Java 8/11 will be happy to test and provide an implementation that can be merged into D4J directly, if having such a validator is important to them.

**Comment by darichey** [comment]
That's fair, but I do think we should provide a default one. That can be done later, separate from this PR.

Is there a use case for it returning `Mono<Boolean>`?

**Comment by napstr** [comment]
I'm not 100% sure if the proper reactive solution for this wouldn't need to run non-blocking, or, since it needs a special key, ppl might want to run it on some kind of microservice over the network and whatnot, so I went with `Mono<Boolean>`. There is however not really a reason to do that and it might as well just be a boolean.

**Review by quanticc — CHANGES_REQUESTED** [review]
Let's go with a boolean return instead of Mono

thanks

**Review by quanticc — APPROVED** [review]

**Comment by napstr** [comment]
Thanks for cleaning that up and merging!

**Pull request merged**
