### PR TITLE
:truck: rename ReactionEmoji to Emoji

### LINKED ISSUE #1031: Rename ReactionEmoji to Emoji
**Feature Description:** 
Rename the ReactionEmoji.class to Emoji.class
**Justification:** 
since ReactionEmoji can be used for messages/buttons/select etc... i think it make more sense that the class need to be rename to a more global name

### PR DESCRIPTION
**Pull request by WeeskyBDW**
**Description:** 
Rename of ReactionEmoji to Emoji including:
    - moving of Emoji class in discord4j.core.object package
    - adding a dummy ReactionEmoji class (who extends of Emoji class) for keeping compatibility
    
**Justification:** 
Because methods in ReactionEmoji wasn't only related to reaction emoji but was more globals, i think it's better to rename the class

close #1031

### CODE REVIEW

**Comment by NovaFox161** [comment]
Potentially relevant commit on the discord docs https://github.com/discord/discord-api-docs/commit/18e13bbeebbd9ae3b329beb628a100914445689b

**Comment by WeeskyBDW** [comment]
> There are several other internal classes that reference ReactionEmoji. If the intent is to migrate over to Emoji instead, should those internal references all be updated as well in this PR? For example: javadocs, class references, variable names, getter/setters, etc.
> 
> Of course, this may require adding more deprecated versions of any public references to preserve backwards compatibility.

sorry for being late but now done

**Comment by Doc94** [comment]
Sorry the mention to a year old PR.... but this is currently ready or need something?

**Comment by WeeskyBDW** [comment]
I forgot about it sorry, iirc i made things and got no return of i need to anything else (i dont anymore follow project acticity as i dont use anymore d4j and Java for creating bots).

Anyway if any change is needed i'll update

**Pull request closed without merging**
