### PR TITLE
Change scope of com.discord4j:stores-api from implementation to api.

### LINKED ISSUE #1200: Dependency com.discord4j:stores-api in /common module seems to be in the wrong scope.
**Expected Behavior:** Some classes in **com.discord4j:stores-api** are exposed in the library binary interface. For example, class **discord4j.store.api.service.StoreService** in **stores-api** is used as public method parameter in class **common/src/main/java/discord4j/common/store/legacy/LegacyStoreLayout.java**. According to [gradle official doc](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies), **stores-api** should be set to scope **api**.

    types used in public method parameters, including generic parameter types 

**Actual Behavior:** **stores-api** has scope **implementation**, this can lead to compilation failures in consumers, as mentioned in offical doc.

### PR DESCRIPTION
**Pull request by HappyHacker123**
**Description:** Change scope of com.discord4j:stores-api from implementation to api.
**Justification:** Fix #1200 according to [gradle official doc](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies).

### CODE REVIEW

**Comment by HappyHacker123** [comment]
@Azn9 @Doc94 Could you please take a look at this pr? Many thanks :)

**Comment by Azn9** [comment]
I'm already here 👻

**Comment by HappyHacker123** [comment]
> I'm already here 👻

Really appreciate your prompt response :)

**Review by quanticc — APPROVED** [review]
Fine with me. Regarding the reason, it's probably an oversight after moving `Store` to the common module, that didn't trigger anything since we use Stores in the context of core module only, where it is configured as `api`.

**Review by Doc94 — APPROVED** [review]

**Comment by Doc94** [comment]
i dont check but this can target 3.2.x?

**Comment by Azn9** [comment]
> i dont check but this can target 3.2.x?

Yeah it should, I'll rebase it

**Pull request merged**
