### PR TITLE
Update guild fields

### PR DESCRIPTION
**Pull request by Shadorc**
**Description:**
- Adds supports for `system_channel_flags` to get the flags of the system channel.
- ~~Adds supports for `rules_channel_id` to get the ID of the channel in which a discoverable server's rules should be found, if present~~.
- Adds supports for `discovery_splash` to get the the discovery splash URL of the guild, if present.

**Justification:** https://github.com/discordapp/discord-api-docs/pull/1262

### CODE REVIEW

**Comment by Shadorc** [comment]
Since `rules_channel_id` does not seem ready to be documented (https://github.com/discordapp/discord-api-docs/issues/1277#issuecomment-576933375), I have removed it.
This pull request is now ready for review.

**Comment by Doc94** [comment]
Well discord now have the public channel (where discord send system messages about new features and other stuff)

**Comment by Shadorc** [comment]
Yes but we still don't know if they are TextChannel, NewsChannel or both 
https://github.com/discordapp/discord-api-docs/issues/1277

**Comment by Doc94** [comment]
Maybe set how to GuildChannel (?

**Comment by Shadorc** [comment]
GuildChannel includes VoiceChannel.
It's better to wait for discord answer

**Comment by Doc94** [comment]
> 
> 
> GuildChannel includes VoiceChannel.
> It's better to wait for discord answer

i mean "GuildMessageChannel" this include all channel for texts.

**Comment by Shadorc** [comment]
We don't know if these channels can be NewsChannel or no, it's better to wait for documentation before merging something that will break in the near future.
Also, I don't think anyone is planning to use this particular field soon

**Comment by Doc94** [comment]
> 
> 
> We don't know if these channels can be NewsChannel or no, it's better to wait for documentation before merging something that will break in the near future.
> Also, I don't think anyone is planning to use this particular field soon

or maybe give the Snowflake, well in client only textchannels works, store or news not show in list of avaible channels in config.

**Comment by Shadorc** [comment]
Do you want to use this feature as soon as possible ? If so, I can give the Snowflake but in the other case I don't know why not wait a little

**Comment by Shadorc** [comment]
Replaced by #624

**Pull request closed without merging**
