### PR TITLE
Switching to Immutable Specs

### PR DESCRIPTION
**Pull request by Alex1304**
Depends on https://github.com/Discord4J/discord-json/pull/92 and https://github.com/Discord4J/discord-json/pull/93

# Description

Reworks the Spec API to use immutable objects. This proposal uses the power of the [Immutables library](https://immutables.github.io) to generate the Spec objects, automatically exposing convenience methods for the user to build those objects intuitively.

# Justification

#693 #585

# Overview

## General structure

Let's say we want to make a `DoActionSpec` applying to an `Entity` that returns some `Result`. The internal structure will look like this:

```java
@SpecStyle
@Value.Immutable(singleton = true)
interface DoActionSpecGenerator extends Spec<DoActionRequest> {
    
    Possible<Snowflake> property1();
    
    Possible<Integer> property2();

    @Override
    default DoActionRequest asRequest() {
        return  ...;
    }
}

@SuppressWarnings("immutables:subtype")
@SpecStyle
@Value.Immutable(builder = false)
abstract class DoActionMonoGenerator extends Mono<Result> implements DoActionSpecGenerator {

    abstract Entity entity();

    @Override
    public void subscribe(CoreSubscriber<? super Result> actual) {
        entity().doAction(DoActionSpec.copyOf(this)).subscribe(actual);
    }

    @Override
    public abstract String toString();
}
```
* `@SpecStyle` is used to configure Immutables to shape our Spec objects in a way that will be consistent and intuitive to the user. The implementation is public while the abstract type is package-private. 
* The Generator interface declares all fields as ~~nullable~~ `Possible` fields. ~~A null field means the value is unspecified/absent~~ If the value of a field is never set explicitly it will automatically default to `Possible.absent()`.
* The `singleton = true` will tell Immutables to generate a `DoActionSpec.create()` factory method without params (only for specs without mandatory parameters), on which the user can chain `.withXxx(...)` calls. But the regular builder `DoActionSpec.builder().xxx(..).build()` will still be available, the user will be able to choose either of them according to their preferences.
* The MonoGenerator abstract class allows to expose a more straightforward API for the user to build specs for the most simple cases. In our example, `Entity` will have two methods for our action, one which signature would be `Mono<Result> doAction(DoActionSpec spec)` and another one which signature would be `DoActionMono doAction()`. The latter is preferred for the most simple and common cases, while the former is more adapted for templating or when the construction requires more complex logic.
* The `@SuppressWarnings("immutables:subtype")` is because having an Immutable extend/implement another Immutable is not officially supported by the library, but I double checked the generated classes to look for consistency problems and I haven't found any, so I just ignored the warning. The abstract `toString()` is also here to remove another kind of warning.

## 3 ways to use Specs

```java
// Option 1: BanQueryMono
member.ban().withReason("ban").block();

// Option 2: BanQuerySpec with copy methods
member.ban(BanQuerySpec.create().withReason("ban")).block();

//Option 3: BanQuerySpec with regular Builder pattern
member.ban(BanQuerySpec.builder().reason("ban").build()).block();
```

## Specs with mandatory parameters

```java
// Mono variant: mandatory parameters are directly included in the method signature
guild.createCategory("category").withPosition(0).block();
gateway.createGuild("guild", region).withIcon(icon).block();

// Copy method variant: use .of(params) instead of .create()
guild.createCategory(CategoryCreateSpec.of("category").withPosition(0)).block();
gateway.createGuild(GuildCreateSpec.of("guild", region).withIcon(icon)).block();

// Builder variant works the same
```
## Collection fields

For the Builder pattern, Immutables automatically generates convenience methods like `addX`. For copy methods, Immutables doesn't offer `withAddX` or similar, but does offer an overload with varargs, which is also a decent option. 

## Multi-parameter fields

Handling fields with multiple parameters, like `MessageCreateSpec#addFile(name, inputStream)`, `EmbedCreateSpec#addField(title, content, inline)` or `GuildCreateSpec#addChannel(name, type)`, was a bit challenging but I found a not-too-messy way to do it.

I create a `DoActionFields` class corresponding to a certain `DoActionSpec`, which contains internal immutable objects grouping the multiple parameters. For files in `MessageCreateSpec` for example it's implemented like this:
```java
@InlineFieldStyle
@Value.Enclosing
public final class MessageCreateFields {

    @Value.Immutable
    public interface File extends Spec<Tuple2<String, InputStream>> {

        static File of(String name, InputStream inputStream) {
            return ImmutableMessageCreateFields.File.of(name, inputStream);
        }

        String name();

        InputStream inputStream();

        @Override
        default Tuple2<String, InputStream> asRequest() {
            return Tuples.of(name(), inputStream());
        }
    }
} 
```
For these immutables, the abstract type is public while the implementation is package-private. When constructing the spec, we can use `.withFiles(File.of(name, inputStream))` for the copy method variant. For the Builder variant, thanks to the `deepImmutablesDetection` flag of Immutables, we can do `.addFile(name, inputStream)` directly without having to do `File.of(...)` manually!

## Removable fields

The last thing is about specs allowing to remove a field. This is applicable for fields like `MemberEditSpec#nickname` or any field in `MessageEditSpec`. With old specs, calling `messageEditSpec.setEmbed(null)` would remove the embed, while not calling the method at all would just leave the old one unchanged. With these new Specs, this behavior can be reproduced by enabling `Possible` encodings from discord-json in the spec package.

# Limitations

Fortunately the only limitations I found are relatively minor, but they are still worth mentioning:
* The "package-private abstract type, public implementation type" approach makes us unable to write our own javadocs on the Spec objects since they are all auto generated.
* Some generated copy methods may be redundant for the Mono variant, for example it is possible to do `entity.doAction().withEntity(entity2)`. I opened an issue on the Immutables repository to request a feature that would allow to disable the generation of specific copy methods, but probably won't happen any time soon https://github.com/immutables/immutables/issues/1303

### CODE REVIEW

**Comment by darichey** [comment]
I know there's still lots to be done, but here's a few initial thoughts.
* I'm not sure if we want to go down the path of including required params in the methods directly. We could have already been doing this with existing specs, but chose not to. imo, this is a bit like how we don't validate, we let Discord do that
* The multi-parameter fields solution is OK, but it would be awesome if we could get that `deepImmutablesDetection` behavior on the Mono and copy method variants too. Maybe we can request it
* I think the removable field behavior will need to be reworked. I'm not a big fan of "null" having a different meaning here, especially if it will be immediately transformed to Possible for the discord-json layer. Is there a reason we can't also use Possible here?

**Comment by Alex1304** [comment]
> I'm not sure if we want to go down the path of including required params in the methods directly. We could have already been doing this with existing specs, but chose not to. imo, this is a bit like how we don't validate, we let Discord do that

The "mandatory parameters" aren't parameters that I arbitrarily picked. If we take `CategoryCreateSpec#name` for example, it is literally impossible to build a `CategoryCreateRequest` internally without specifying a `name`, because the json field isn't a `Possible` nor an `Optional`. So it doesn't make sense to have `CategoryCreateSpec#name` return a `@Nullable`. But if a field isn't nullable, it becomes required, so Immutables will generate a `.of` method with that field as parameter. The old specs are currently throwing an exception upon calling `asRequest()` if category name isn't specified, so the error happens before the request is even sent to Discord.

> The multi-parameter fields solution is OK, but it would be awesome if we could get that deepImmutablesDetection behavior on the Mono and copy method variants too. Maybe we can request it

The fact that it isn't available for copy methods is inherent to the fact we haven't a `withAddXxx` method. There is only `.withXxx(Iterable)` and `.withXxx(varargs...)` available.

> I think the removable field behavior will need to be reworked. I'm not a big fan of "null" having a different meaning here, especially if it will be immediately transformed to Possible for the discord-json layer. Is there a reason we can't also use Possible here?

I did try to make fields `@Nullable Possible<T>`, but the value will default to `null` instead of `Possible.absent()` if the method is never called...

**Comment by Alex1304** [comment]
Nevermind, this worked

```java
@Value.Default
@Nullable
default Possible<String> content() {
    return Possible.absent();
}
```

guess I'll go this route then

**Comment by darichey** [comment]
> Nevermind, this worked
> 
> ```java
> @Value.Default
> @Nullable
> default Possible<String> content() {
>     return Possible.absent();
> }
> ```
> 
> guess I'll go this route then

In discord-json, we use `Possible<Optional<T>>` to support fields that are both "optional" (by Discord's terminology) and nullable. I think we should do the same here. We also have something in discord-json that allows us to make `absent()` the default value for `Possible` fields without all of that ceremony. I took a quick look but couldn't find it (cc @quanticc). Ideally, we could reuse all of the encoding stuff from discord-json.

**Comment by Alex1304** [comment]
> In discord-json, we use `Possible<Optional<T>>` to support fields that are both "optional" (by Discord's terminology) and nullable. I think we should do the same here. We also have something in discord-json that allows us to make `absent()` the default value for `Possible` fields without all of that ceremony. I took a quick look but couldn't find it (cc @quanticc). Ideally, we could reuse all of the encoding stuff from discord-json.

I first thought of using `@Nullable` to be consistent with the old behavior of using `null` to remove the field, but if in the end you prefer `Optional` I can change it without problem. I let you see with quanticc regarding this decision.

**Comment by quanticc** [comment]
Artifact `discord-json-encoding` is now available on both branches https://oss.sonatype.org/content/repositories/snapshots/com/discord4j/discord-json-encoding/

**Comment by Alex1304** [comment]
I found a way to fix it, I need this PR to be merged so I can continue: https://github.com/Discord4J/discord-json/pull/92

**Comment by Alex1304** [comment]
Hm, I don't see `MessageReferenceSpec` being used anywhere in the project except inside the implementation of  `MessageCreateSpec#setMessageReference(Snowflake)`, is it necessary to keep it?

**Comment by quanticc** [comment]
No need to keep it then

**Comment by Alex1304** [comment]
All specs are now done, marking this PR as ready for review.

**Comment by Alex1304** [comment]
Found another sneaky issue regarding PossibleOptional encoding. If you do `.withNickname(null)` it will result in an ambiguous method call error, because Java can't choose between the nullable overload and the `Possible<Optional<T>>` overload. I guess the solution would be updating the nullable overload to use a different naming, e.g `@Encoding.Naming("*OrNull")` so we do `.withNicknameOrNull(null)` instead. Can I include this change in PR #93 or should I open a separate one?

**Comment by quanticc** [comment]
It's ok to add it to Discord4J/discord-json#93

**Comment by Alex1304** [comment]
Ok. I noticed I also need to create a new encoding class for `Possible<Optional<List<T>>>`, I'll add both to that PR.

**Comment by Alex1304** [comment]
It works very well, methods are now properly generated. Except that Immutables doesn't retain the `@Nullable` annotation, so the IDE gives warnings when passing null... screenshot

Would it be a good idea to remove the `@NonNullApi` annotation on the spec package to circumvent this?

**Comment by Alex1304** [comment]
Alright, so I restored old specs under `discord4j.core.spec.legacy` and renamed all classes to `LegacyXxxSpec` to avoid name clashes. Methods that use old specs have been restored and marked `@Deprecated`.

The package/class name change shouldn't affect most users using simple lambda expressions, but the compiler should be explicit enough for users that import the classes.

Now hoping this can be shipped in 3.2 safely 👀

**Comment by Alex1304** [comment]
Btw https://github.com/Discord4J/discord-json/pull/93 needs to be merged for this one to build successfully

**Comment by Alex1304** [comment]
Whoops, just realized I accidentally changed `MessageCreateSpec#nonce` from Snowflake to String... Should I change it back to Snowflake? Discord docs doesn't require it to be a snowflake specifically, and on discord-json layer it's a String, not an Id, so idk

**Comment by danthonywalker** [comment]
```
The "package-private abstract type, public implementation type" approach makes us unable to write our own javadocs on the Spec objects since they are all auto generated.
```
What does this mean, exactly? Preferably what I would like is Javadocs, at the very least, generated for the finalized methods on each respective object. For example,
```
// Option 1: BanQueryMono
member.ban().withReason("ban").block();

// Option 2: BanQuerySpec with copy methods
member.ban(BanQuerySpec.create().withReason("ban")).block();

//Option 3: BanQuerySpec with regular Builder pattern
member.ban(BanQuerySpec.builder().reason("ban").build()).block();
```
I would like a Javadoc generated on all 3 methods. It doesn't have to be an unique doc, it can just be the same copy/pasted one indicating how to use any of these 3 options.
This is especially important when we link to Javadocs. For something like the `Guild` object, the method count is going to explode and the Javadoc will become much larger. I would be much more at easy if there was docs generated.

**Comment by Alex1304** [comment]
I just meant that if some specific method requires a more descriptive Javadoc than the one auto-generated by Immutables, it won't be possible to override it. Writing custom javadoc on the abstract type will be visible on getters, but not on builder setters and withXxx methods.

**Comment by darichey** [comment]
In trying to build locally, I brought this up to date with master. That ended up being a bit nontrivial, so I went ahead and pushed those changes here. @Alex1304, could you check that everything looks good with that commit?

Regarding javadoc, I agree that it would be ideal if we could write docs for those methods. We should ask the immutables maintainers if this is possible, or at least request that it be. That said, a bigger concern with javadoc is that currently it seems no javadoc is included for the generated classes at all. Here is an example:
image

From a quick search, I couldn't find any information about this issue.

**Comment by Alex1304** [comment]
Merged latest master, resolved all conflicts and everything builds fine.

**Comment by Alex1304** [comment]
> Regarding javadoc, I agree that it would be ideal if we could write docs for those methods. We should ask the immutables maintainers if this is possible, or at least request that it be. That said, a bigger concern with javadoc is that currently it seems no javadoc is included for the generated classes at all. Here is an example:
> image
> 
> From a quick search, I couldn't find any information about this issue.

This sounds like the Gradle javadoc task isn't picking up the generated sources or something

**Review by quanticc — APPROVED** [review]
Thanks a lot !

**Review by darichey — APPROVED** [review]
Let's get this merged! We can continue to iterate and fix any smaller issues in 3.2.x.

**Pull request merged**
