### PR TITLE
Add default AllowedMentions option

### PR DESCRIPTION
**Pull request by WinteryFox**
**Description:** Added a default AllowedMentions field to the builder.

**Justification:** This way users won't have to manually set an AllowedMentions in every createMessage call when for example they want to disable all pings on every message.

### CODE REVIEW

**Comment by darichey** [comment]
I think the core builder should accept `AllowedMentions`. Not sure if `RestClientBuilder` should retain the data version.

**Comment by WinteryFox** [comment]
Why? The Core builder inherits from the Rest one, and both can use allowed mentions.

**Comment by darichey** [comment]
We dont expose Data in core. There's asymmetry in how to set the default allowed mentions and how to do it per message. That's not good.

**Comment by WinteryFox** [comment]
Ohh I see, that's what you mean. How else do you want to implement this for Rest then? Since the AllowedMentions is not exposed to Rest, just the Data.

**Comment by quanticc** [comment]
If we want rest module to support this we need to:
- Move AllowedMentions to rest
- Update RestClient to hold a RestResources instance so it can query above value from Config
- Update RestClientBuilder::createRest function to build this new RestClient
- Use it from RestChannel class that will call RestResources

Alternatively, if this is a core-only feature, it shouldn't live on RestClientBuilder.

**Comment by WinteryFox** [comment]
I would probably prefer the former option, I don't see why this should be excluded from rest when it is supported by Discord.

**Comment by quanticc** [comment]
AllowedMentions was moved to rest module, so work can be resumed using the following as guide:

> * Update RestClient to hold a RestResources instance so it can query above value from Config
> * Update RestClientBuilder::createRest function to build this new RestClient
> * Use it from RestChannel class that will call RestResources

**Comment by WinteryFox** [comment]
I'll have a looksie at doing this during the weekend

**Comment by quanticc** [comment]
We're still interested in merging this PR, let us know if you need any help

**Comment by quanticc** [comment]
Superseded by e9d7a32

**Pull request closed without merging**
