### PR TITLE
Update BOM for Reactor and Member Logic Fixes

### PR DESCRIPTION
**Pull request by EasternGamer**
**Description:** 
- Updated Reactor BOM
- Added .equal override for PartialMember.java to account for guild ID. 
- Made .equal override in User.java no longer final to enable override in PartialMember.java

**Justification:**
- The current version used of Reactor has security vulnerabilities. (Though, I'm not sure why the version used it so old)
- Comparing to members with .equals() can falsely state that two members that are the same user, but in different guilds are the same.
- Impossible to make the above happen without removing the final modifier.

### CODE REVIEW

**Review by Azn9 — APPROVED** [review]

**Comment by Azn9** [comment]
This should target 3.2.X, I'll rebase it

**Comment by Doc94** [comment]
This require a rebase but the source branch is master.
Please open a new PR using a new branch of source.

**Comment by Azn9** [comment]
@Doc94 I already rebased this on 3.2.x, even if the branch name is "master"
Maybe this needs another rebase, in that case I'll do it (I cannot see it before re-opening the pr)

**Comment by Azn9** [comment]
So, no, it does not need a rebase and already targets 3.2.x with only one added commit, lgtm

**Comment by Doc94** [comment]
> So, no, it does not need a rebase and already targets 3.2.x with only one added commit, lgtm

okay, when try test i cannot set the branch in my setup for the branch name... then if run correctly then can be merged.

**Comment by Azn9** [comment]
> > So, no, it does not need a rebase and already targets 3.2.x with only one added commit, lgtm
> 
> okay, when try test i cannot set the branch in my setup for the branch name... then if run correctly then can be merged.

You can try with:
`git remote add EasternGamer https://github.com/EasternGamer/Discord4J.git`
`git fetch EasternGamer`
`git checkout -b pr_1180 EasternGamer/master`

**Pull request merged**
