### PR TITLE
Add support for select menus

### PR DESCRIPTION
**Pull request by darichey**
**Description:**
Adds support for select menus.

Depends on https://github.com/Discord4J/discord-json/pull/98

**Justification:**
https://github.com/discord/discord-api-docs/pull/3200

### CODE REVIEW

**Comment by darichey** [comment]
If you want to use (and provide feedback on 🙂) select menus, you can use the snapshot version `3.1.7-select-menus-SNAPSHOT`
(see https://docs.discord4j.com/using-latest-snapshots). See [`ExampleSelectMenu`](https://github.com/Discord4J/Discord4J/blob/feature/select-menus/core/src/test/java/discord4j/core/ExampleSelectMenu.java) for a quickstart example.

**Review by quanticc — APPROVED** [review]

**Comment by sokratis12GR** [comment]
Lovely, but seems that the selected menu changes don't stay over after the user selects them 
Also the `onSelectMenuEvent`? is missing currently (so in order to execute custom interactions via the react way is by doing running the component event).

Maybe? Suggestions:

- [1] Allow the setting of default value(s) via the SelectMenu object, based on the discord docs.. that's does not seem possible with the current limitations.

- [2] Introduce an "easier way"? to obtain the selected value(s) based on the min/max that are set (or 1-1 if none are set), looking at the discord docs that seems to be as far as discord allows, hmm.

Lovely work tho ^^

**Comment by sokratis12GR** [comment]
Actually after further testing, the selected choices don't execute if selected and then the menu is pressed to be closed.
Select -> Click Select Menu to close -> Choices remain but code not executed
Select -> Press way -> Executes code, but choices don't remain

**Comment by darichey** [comment]
> Also the onSelectMenuEvent? is missing currently

Good catch, I'll add this to ReactiveEventAdapter 

> [1] Allow the setting of default value(s) via the SelectMenu object

Discord models this by having each option indicate whether it is default or not. Do `Option.ofDefault` and `Option#withDefault` not cover this?

> [2] Introduce an "easier way"? to obtain the selected value(s) based on the min/max that are set

If I understand you correctly, I don't think there's much we can do here short of creating a class for every possible configuration of min/max. I think getting a list from `SelectMenuInteractEvent` is fairly ergonomic. Is there something else you had in mind?

Finally, your issues with selection sound like a Discord bug. There's nothing we can do about it, we either get the event or we don't. I'd ask in the selects channel if that behavior is intended.

**Comment by sokratis12GR** [comment]
> Discord models this by having each option indicate whether it is default or not. Do `Option.ofDefault` and `Option#withDefault` not cover this?
They do that, but you need direct access to the option entries, err cannot "edit" or change the default value after the initial message has been set, this might as well be a discord limitation.
> If I understand you correctly, I don't think there's much we can do here short of creating a class for every possible configuration of min/max. I think getting a list from SelectMenuInteractEvent is fairly ergonomic. Is there something else you had in mind?
What I had in mind was like a custom `SelectionValue` if the max amount of selectable values would be a single one and return itself, if there were more cases a list of `SelectionValue`/`String` otherwise I guess just always getting the first element SelectMenu.getOptions().get(0) would suffice for a single max selects menu.

Hope that clarifies the second question ^^

**Comment by sokratis12GR** [comment]
Ah so got some clarification over at the `selects` section, given that selects are stateless and them confirming that the client will lose its setting once they refresh the client, and/or edit a message.

**Pull request merged**
