### PR TITLE
Bugfix/time monotonicity

### PR DESCRIPTION
**Pull request by koyagami**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature thoroughly
  * There is nothing that can really be tested that is not just testing that Java compiles
    in the way it is supposed to compile. All that has been changed is one entry to the gitignore, one 
    method changed from package-private to public, and one simple accessor added to the 
    DiscordClient implementation. Nonetheless, I will provide proof that this has not _broken_ 
    anything in the existing client.

image

image

**Issues Fixed:**
- #464 
- This provides information that would be useful for implementing #462, but does not expose it publicly. 

### Changes Proposed in this Pull Request
* Implement monotonic time difference measurements in the gateway without affecting existing dependencies on the package-private accessor that uses a non monotonic time source.
* Implement monotonic time differences in SimpleBucket.
* Added `*.iml` to `.gitignore` as you probably don't want those being uploaded here.

I hope I have not forgotten anything important. If anything needs to be discussed, you can alternatively ping `@Espy#7235` in your Discord guild, as that is my account, if that is easier.

Thanks :)

### CODE REVIEW

**Comment by koyagami** [comment]
Hopefully fixed the conflicts that occurred.

**Comment by quanticc** [comment]
Do you see any potential issue with keeping both `lastAck` and `lastSent` (no extra fields added) but using nanoTime instead of currentTimeMillis?

**Comment by koyagami** [comment]
as I mentioned in the commit, the issue appears to be (I might be wrong) that if the following occurred...

1. send heartbeat, record time
2. get heartbeat ack, record time
3. send heartbeat, record new time
4. request heartbeat latency, do `ack time` - `new sent time`. Value is negative and incorrect
5. get heartbeat ack

...then we'd have no way to get an accurate value. The benefit of storing the latency directly is we only update it once we have the entire information base we need to make the calculation :)

**Comment by danthonywalker** [comment]
Accidental closure from deleting v3 branch.

**Comment by quanticc** [comment]
Going back to #464 as the API has changed a lot by now. Sorry we didn't focus on this item before but we had  higher priority stuff for gateway module.

**Pull request closed without merging**
