### PR TITLE
Started README Overhaul

### PR DESCRIPTION
**Pull request by danthonywalker**
READMEs are important for open-source projects. They provide a first impression for their projects. They should tell you what it is, how to get it, and how to use it. It should be inviting, easy to follow, and also nice to look at. I plan on revamping the README to include a *lot* more examples and to just flesh out ways to make ourselves stand out and provide the essential question, *"Why should I use Discord4J?"

### CODE REVIEW

**Comment by danthonywalker** [comment]
After some discussion I'm scraping and redoing.

* I forget to most people enterprise is a bad word. :/
* Quick examples should be quicker. Cut out explanations, only show text and action. Explanations can come later.
* More eye-catching opener. How many buzzwords can we fit in?!
* More emphasis on you don't need to learn Reactor to use D4J. Maybe stop saying it so much to just imply that...?
* In general README should read quicker. I was using https://github.com/earthly/earthly as a pseudo-reference but I guess that doesn't work well...

In general, I have no idea what I'm doing. Time to experiment ^.^

**Comment by quanticc** [comment]
Looks ready, what's pending?

**Comment by danthonywalker** [comment]
What would you like added? There's some stuff missing feom the original README, but how essential are they?

**Comment by quanticc** [comment]
I like the content in its current state. Maybe some other links to wiki pages, but I'm not sure what items should be included.

Before merging though, we have a template to update it on version change though so you could copy it there.

For the future it would be interesting to also include the code examples by copying them from a source file.

**Pull request merged**
