### PR TITLE
Provide a new in-memory `StoreLayout` implementation

### PR DESCRIPTION
**Pull request by Alex1304**
During the past days I tried to rework entirely the store layout implementation that I originally proposed in the first PR. The issue with the old one was the increase in memory usage, I also found some other issues involving thread safety.

## Content description
* This new version drops the `Storage` approach and brings back the 9-Map structure with Long2 keys, with two additional Maps that store IDs per guild and per channel respectively, in order to optimize `getXInGuild` / `getXInChannel` and to allow faster cleanup when a guild or a channel is deleted.
* Everything is entirely thread-safe. All create/delete operations affecting the same entity type within the same guild are forced to execute sequentially using `synchronized` statements, and update operations are done in an atomic way using CAS. 
* As opposed to the first version, it doesn't store the `*Data` objects directly, it converts them to custom objects that are similar except that they store all snowflakes as `long`, and some fields are made mutable to avoid recreating the whole object when only 1 field is updated (for example `ChannelData#lastMessageId` or `MessageData#reactions`). Those mutable fields are of course mutated in an atomic manner.
* If there's one thing that I kept from the first version however, is the concept of making members and presences share the same reference of user data. The user store uses weak values so that they can be automatically removed if no member or presence reference them anymore (which means that the bot no longer shares any server with the user). I extended this feature to message author, emoji creator, and channel recipients (even if DM channels are normally never cached, that's more of a "just in case" thing). 

## Justification

The PR #788 reworks the store API, and currently there is no implementation to use by default for local/non-distributed bots. The purpose of this PR is to provide one that is at least as good as the old stores in terms of read/write performances and memory footprint.

## Results

I did some performance tests with my prod bot's token which is in almost 10k servers. First I compared the total JVM size in the task manager between old 3.1 stores and this new one. With the old stores it takes 1.7 GB of RAM while it takes 1.4 GB with the new impl, so that's a ~17% improvement. I then looked more deeply with `jmap` to see the heap usage per object type, and I realized that most of the gain was obtained by storing snowflakes as long, the total space taken up by `java.lang.String` was almost divided by 3.

I'd say that the most notable tradeoff to this gain of performance is the complexity of the code, but I tried my best to keep it as structured as possible so hopefully you won't have too much struggle reviewing it.

### CODE REVIEW

**Comment by quanticc** [comment]
Thanks for revisiting this area. We want to move ID storage as longs internally but from the discord-json project: discord-json#20 - I've done some tests using virtual fields and they seem to work.

Once that "comes for free" in Data objects, I would like to measure if going back to mutability provides some benefit. I'm initially cautious about this switch if it's not a significant memory usage improvement.

**Comment by Alex1304** [comment]
I'm aware that you're working on switching snowflakes to long at discord-json level. If you're wondering about the justification of having custom `StoredXxxData` objects, it's to allow maximum flexibility in terms of optimization for this very specific implementation (those custom objects are package-private). Besides converting snowflakes to long, it supports atomic mutability but only on specific fields (the vast majority of them are actually still immutable), and it uses other specific optimizations such as storing a reference of an existing user data in cache instead of storing a possibly stale copy of it. That being said, I don't see a reason to switch discord-json objects back to mutable, and I believe those implementation-specific entities will still be useful even after the snowflake switch.

**Comment by quanticc** [comment]
Now that #788 was merged, can you rebase this over master making the diff easier to review?

**Comment by Alex1304** [comment]
Done :slightly_smiling_face:

**Comment by quanticc** [comment]
I'll put this PR on hold awaiting for more reviews, even though I'd like to test locally if this implementation holds without any need for explicit synchronization.

My focus is now on Discord4J/discord-json#34 and #796 so I need some stability from the Stores side to work on those

**Comment by Alex1304** [comment]
Updated the implementation, now it doesn't use synchronization anymore and it's 100% immutable again. In the end I believe the overhead caused by the use of copy methods instead of mutable methods is not significant considering this is an in-memory implementation intended for local/non-distributed bots. Memory usage will be a much more important criteria than speed imo, as long as the latter is acceptable.

This will need to be tested in real conditions before it can be merged, with a monitoring of memory usage and potential slowdowns (and potential bugs in the implementation itself because it's likely I broke something in this update).

**Comment by quanticc** [comment]
Can you leave some comments about why are WithUser/AtomicReference needed

**Comment by Alex1304** [comment]
Quite a lot of entities contain user data in them, such as author in MessageData, emoji creator in EmojiData, user in MemberData, PresenceData... each entity would store its own copy of UserData, which can be very redundant. Also, if let's say a GuildMemberUpdate is received, the UserData contained in MemberData will be updated, but not the UserData in messages authored by this same user, nor their presence or voice state... Having a WithUser/AtomicReference allows to store a reference to an existing user in the user cache instead of a whole copy of UserData. This not only significantly reduces memory usage, but also any update made in user cache will reflect in all other entities

**Comment by Alex1304** [comment]
Btw there's something I need to fix. When I return old state I return the result of computeIfPresent directly, but I forgot that method returns the new value and not the old one...

**Review by quanticc — APPROVED** [review]
Thanks! we're ready to merge this for RC1

**Pull request merged**
