### PR TITLE
AuditLogEntry.getOption() does not return the right class types

### PR DESCRIPTION
**Pull request by florianhartung**
**Description:** 
The AuditLogUtil#createOptionMap now returns a Map<String, ?> with the values being of the correct class type.
Before the returned Map was basically always a Map<String, String>.

**Justification:**
The value class types of the Map now correspond to the specified types in the pre-defined OptionKey[s].
Therefore Issue #851 is fixed.

### CODE REVIEW

**Comment by Shadorc** [comment]
According to the documentation (https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-optional-audit-entry-info), `count` is a string. If it is finally converted as an integer, maybe `members_removed` could benefit the same change?

**Comment by florianhartung** [comment]
> According to the documentation (https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-optional-audit-entry-info), `count` is a string. If it is finally converted as an integer, maybe `members_removed`, `delete_member_days` and `type` could benefit the same change?

I didn't check whether `count` would be a string or an integer because it was already marked as an integer, but what do you mean by them benefiting the same change? Because they all need to be parsed to a Snowflake?

**Comment by Shadorc** [comment]
Not as Snowflake, but maybe as integer because it's what they represent, like `count`

**Comment by florianhartung** [comment]
> Not as Snowflake, but maybe as integer because it's what they represent, like `count`

Ohh I misunderstood you. I will be able to look into that tomorrow.

**Comment by darichey** [comment]
This looks good so far. I agree that we should also convert the other fields which are really integers. Also, could you make similar changes to ChangeKey? I believe it has the same problems. Thanks!

**Comment by darichey** [comment]
I'm picking up the rest of this in #899. Thanks for starting this!

**Pull request closed without merging**
