### PR TITLE
Redesigned command Module

### PR DESCRIPTION
**Pull request by danthonywalker**
**Description:**
Redesigned the command module slightly. Currently, this is **NOT** meant to be merged, as it is missing Javadocs and an `util` abstract implementation similar to what existed before. This PR is just currently open to encourage discussion.

**Justification:**
The command module provided too little in the way of interoperability between `CommandProvider` implementations. This slight redesign helps remedy that and also trims away some unnecessary fat.

### Added HelpPage
A help system is what arguably ties all commands for any command system together. Previously, only `CommandProvider` implementations could display help pages for commands under their system, but if there were multiple implementations then:
A) The help systems worked drastically different
B) Could not represent the help for *all* commands in the system (all commands under all `CommandProvider` implementations)

This PR solves this by adding a `HelpPage` that `CommandCategory` (explained later) can optionally provide for a `CommandProcessor` (explained later) to process. It can:
A) Provide all `HelpPage`s immediately available
B) Provide a `HelpPage` for a particular command
C) Provide a `HelpPage` that represents itself
D) Provide a `HelpPage` instead of a `Command` when `provide` is invoked to represent "failed" command executions

This allows a `HelpPage` to be provided under any circumstance that a `CommandProcessor` would require one.

### Renamed CommandProvider to CommandCategory
To go hand-in-hand with the addition of `HelpPage`, `CommandProvider` has been renamed to `CommandCategory`. This is so it's more clear to understand what kind of `Command` instances should fall inside any given `CommandCategory`. It additionally provides a way to introduce some sort of "category" system for help pages, which most bots commonly implement. Of course, `CommandProcessor` can ignore such concepts.

### Renamed CommandDispatcher to CommandProcessor
`CommandDispatcher` has been renamed to `CommandProcessor` to emphasis its importance in the system. It is the centralized place for command processing of any type. It therefore also has a lot more power than it did previously. It is responsible for getting commands, executing commands, processing `HelpPage` instances (and when to obtain them), and other responsibilities.

### Removed CommandErrorHandler
To further emphasis the importance of `CommandProcessor`, `CommandErrorHandler` was removed. Previously, a `CommandDispatcher` could simply ignore any given `CommandErrorHandler`, and that was valid. Really, it should be up to the individual implementations of `CommandProcessor ` to decide how to handle errors. Each individual implementation could optionally even provide a way to manipulate that behavior through some abstract method, but it should not be its own interface.

### Trimmed CommandBootstrapper
`CommandBootstrapper` has been slimmed down to only exposing necessary components. Since `categories` is thread-safe, there was no real reason to have the varying `(add/remove)CommandProvider` methods. Additionally, such methods masked the returns of the underlying implementation so there was no way to gauge whether or not an implementation was truly added or removed. Because of `CommandErrorHandler` removal, that implementation was removed.

### CODE REVIEW

**Comment by austinv11** [comment]
I think that if we are redesigning the module in its entirety, we should have more conceptual design exercises before implementing it to clearly define goals as well as steps to take in reaching such goals.

**Comment by danthonywalker** [comment]
What goals do you have in mind?

**Comment by austinv11** [comment]
That's something we need to figure out. We should take a step back from the module as a whole and ignore the current impl (including yours) for now, mock up user stories and see what our current options have, what they are missing and see where to go from there.

**Comment by danthonywalker** [comment]
Some serious rethinking of this module is required and will be a while (maybe 3.1, or even 3.2) that this will see the light of day in some form.

**Pull request closed without merging**
