### PR TITLE
Designated internal Classes

### PR DESCRIPTION
**Pull request by danthonywalker**
Creates an `internal` package for internal API use. This is to help provide a marker for classes that are either unstable or should not be used publicly. Using Java 9+ modules we could even section off the package completely, if desired. In fact I would like in the future to adjust the Javadoc generation to ignore the package and its subpackages for a cleaner Javadoc for core.

This also comes with the introduction of `DiscordClient#getServiceMediator` to allow users to access these internals if they wish, but is the only method in the entirety of the public user space that is not guaranteed any sort of API stability.

### CODE REVIEW

**Comment by GrandPanda** [comment]
If `DiscordClient#getServiceMediator()` exists, how could the `internal` package not be exported?

**Comment by GrandPanda** [comment]
I'm not sure that this is the best approach to take to solve this problem. We had an `internal` package in v2 as well which caused some pain for people. I understand the idea that we simply document it as unstable and that absolves us of responsibility, but I think we can come up with something better.

As an example (and an idea I haven't thought out fully 🙂), would this distinction be better modeled with another subproject/module?

**Comment by austinv11** [comment]
> As an example (and an idea I haven't thought out fully 🙂), would this distinction be better modeled with another subproject/module?

I think that might be too clunky for something that's fairly small

**Comment by quanticc** [comment]
I would commit getServiceMediator for now as this is a separate discussion.

If the goal is to mark unstable/unsupported classes we should use annotations instead.

**Comment by GrandPanda** [comment]
I think the getServiceMediator discussion is tied to this because ServiceMediator's visibility must be modified (and it may not be as useful if you can't access certain things from ServiceMediator because of *their* visibility).

**Pull request closed without merging**
