### PR TITLE
Restructure Events

### PR DESCRIPTION
**Pull request by danthonywalker**
This PR is for a restructuring of events. Have certain events extend/implement different "types" that logically makes sense. For example, a `TextChannelCreateEvent` is both a `ChannelEvent` and a `GuildEvent`.

### CODE REVIEW

**Comment by GrandPanda** [comment]
These changes need more thought to be relevant to the [use case](https://discordapp.com/channels/208023865127862272/451125724766535710/547842301662068741) which prompted them. For example, `RoleEvent`s will not be picked up by listening to `GuildEvent` even though they are "contained" to a guild and have the appropriate ID available.

Personally, I am concerned with creating a complicated hierarchy for events again.

**Comment by danthonywalker** [comment]
Agreed. Although I don't think it'll become necessarily complicated. Just a hierarchy that makes sense. The only thing I want to avoid is what happened in v2 (i.e., a MessageEvent extending GuildEvent)

**Comment by danthonywalker** [comment]
For a while I've wanted to change events to have a better hierarchy structure tbh. I think this PR can expand to incorporate some of those ideas to make the hierarchy make intuitive sense and providing necessary abstractions as/if they are needed.

**Comment by danthonywalker** [comment]
3a97647 comes with a total restructure of events. On my first pass I logically grouped and extended/implemented Events to others that make intuitive sense.

**Comment by danthonywalker** [comment]
eventhierarchy

**Comment by GrandPanda** [comment]
I don't see the point in this added complexity. The changes aren't relevant to the original use case. What use cases *does* it cover? Who stands to benefit?

Alternative proposal: Remove the existing `GuildEvent`, `ChannelEvent`, etc. and have no hierarchy (besides `Event`), since it isn't useful in its current state. Leave the hierarchy and utilities up to some previously-discussed "util events" module. Core stays closer 1:1 with Discord.

**Comment by danthonywalker** [comment]
I'll accept that last proposal.

**Comment by GrandPanda** [comment]
The solutions to the problems presented here will be addressed in another PR.

**Comment by WinteryFox** [comment]
If there's no hierarchy, it will be impossible to make things like listeners for MessageEvent, I have a few use cases in which I need a general MessageEvent because I do not know whether I'm listening for a ReactionAddEvent, MessageEditEvent etc.
Case in point, not having any hierarchy sounds like a bad idea to me.

**Comment by GrandPanda** [comment]
That isn't useful in today's hierarchy because they are simply markers anyways.

**Pull request closed without merging**
