### PR TITLE
Add utility class for creating timestamp markdown strings from java.time.Instant

### PR DESCRIPTION
**Pull request by Masterzach32**
**Description:** Adds `Timestamp.java` in `discord4j.common.util`. This PR targets D4J 3.1.x, however it requires no changes to merge with 3.2.x

Example: 

```java
Timestamp.of(Instant.now()) // returns "<t:xxxxxxx>"
Timestamp.of(Instant.now(), "F") // returns "<t:xxxxxxx:F>"
Timestamp.longDateTime(Instant.now()) // returns "<t:xxxxxxx:F>"
```

**Justification:**
https://github.com/Discord4J/Discord4J/issues/941
https://github.com/discord/discord-api-docs/blob/master/docs/Reference.md#message-formatting

### CODE REVIEW

**Review by quanticc — CHANGES_REQUESTED** [review]
Thanks for the PR, only a minor change is needed: we need to remove `@NonNull` usage and instead apply it to the package using a package-info.java file, we forgot to add it.

```java
@NonNullApi
package discord4j.common.util;

import reactor.util.annotation.NonNullApi;
```

**Review by quanticc — APPROVED** [review]

**Comment by darichey** [comment]
Would it make more sense for this to be an enum? Something like `TimestampFormat.LONG_DATE_TIME.format("...")`, more in the style of `java.time`. I think the only real advantage comes when considering something in the future like #751 where we will need to have something concrete to pass back to the user (i.e., we will have something like `TimestampToken`. What would it contain under this current PR?)

**Comment by Masterzach32** [comment]
Something like this maybe?

```java
public enum TimestampFormat {
    DEFAULT(""),
    SHORT_TIME("t"),
    LONG_TIME("T"),
    SHORT_DATE("d"),
    LONG_DATE("D"),
    SHORT_DATE_TIME("f"),
    LONG_DATE_TIME("F"),
    RELATIVE_TIME("R");

    private final String style;

    TimestampFormat(String style) {
        this.style = style;
    }

    public String getStyle() {
        return style;
    }

    public String format(Instant instant) {
        if (style.isEmpty())
            return "<t:" + instant.getEpochSecond() + ">";
        else
            return "<t:" + instant.getEpochSecond() + ":" + style + ">";
    }
}
```

I think I like this solution better

**Comment by darichey** [comment]
I think that looks good!

**Review by darichey — APPROVED** [review]

**Pull request merged**
