### PR TITLE
Update bot stats and version table in README

### PR DESCRIPTION
**Pull request by NovaFox161**
Add "interactions" section to d4j version table since discord is pushing this major feature set.

And update the large bots section with more recent statistics since its been several months since its original inclusion.

### CODE REVIEW

**Review by quanticc — CHANGES_REQUESTED** [review]
Thanks, we also need to update the [template](https://github.com/Discord4J/Discord4J/blob/master/.github/README_TEMPLATE.md)

**Comment by NovaFox161** [comment]
Oops, forgot about that. I'll get that updated in a bit

**Comment by NovaFox161** [comment]
template file has been updated now

**Comment by Shadorc** [comment]
You can add "before its shutdown in August 2021" for Shadbot, like you did with Groovy
Closing https://github.com/Discord4J/Discord4J/pull/994

**Review by quanticc — APPROVED** [review]

**Pull request merged**
